import { DEFAULT_ITEM_PER_PAGE } from "./constant"

export const productList = [
  {
    itemsPerPage: DEFAULT_ITEM_PER_PAGE,
    total: 1000,
    hasMore: true,
    productList: [
      {
        id: 1,
        name: "E150",
        pictureUrl: "http://dummyimage.com/206x100.png/dddddd/000000",
        discountPrice: 51689000,
        type: "Ford",
      },
      {
        id: 2,
        name: "Impreza",
        pictureUrl: "http://dummyimage.com/216x100.png/dddddd/000000",
        discountPrice: 28785000,
        type: "Subaru",
      },
      {
        id: 3,
        name: "Metro",
        pictureUrl: "http://dummyimage.com/234x100.png/5fa2dd/ffffff",
        discountPrice: 35268000,
        type: "Chevrolet",
      },
      {
        id: 4,
        name: "LR4",
        pictureUrl: "http://dummyimage.com/231x100.png/5fa2dd/ffffff",
        discountPrice: 16155000,
        type: "Land Rover",
      },
      {
        id: 5,
        name: "3 Series",
        pictureUrl: "http://dummyimage.com/147x100.png/5fa2dd/ffffff",
        discountPrice: 19605000,
        type: "BMW",
      },
      {
        id: 6,
        name: "Hombre",
        pictureUrl: "http://dummyimage.com/131x100.png/cc0000/ffffff",
        discountPrice: 79475000,
        type: "Isuzu",
      },
      {
        id: 7,
        name: "LS",
        pictureUrl: "http://dummyimage.com/225x100.png/ff4444/ffffff",
        discountPrice: 36740000,
        type: "Lincoln",
      },
      {
        id: 8,
        name: "Expedition",
        pictureUrl: "http://dummyimage.com/117x100.png/dddddd/000000",
        discountPrice: 17510000,
        type: "Ford",
      },
      {
        id: 9,
        name: "Regal",
        pictureUrl: "http://dummyimage.com/202x100.png/5fa2dd/ffffff",
        discountPrice: 55489000,
        type: "Buick",
      },
      {
        id: 10,
        name: "Canyon",
        pictureUrl: "http://dummyimage.com/166x100.png/5fa2dd/ffffff",
        discountPrice: 42838000,
        type: "GMC",
      },
      {
        id: 11,
        name: "Navigator",
        pictureUrl: "http://dummyimage.com/166x100.png/cc0000/ffffff",
        discountPrice: 52513000,
        type: "Lincoln",
      },
      {
        id: 12,
        name: "FJ Cruiser",
        pictureUrl: "http://dummyimage.com/245x100.png/cc0000/ffffff",
        discountPrice: 69718000,
        type: "Toyota",
      },
      {
        id: 13,
        name: "TSX",
        pictureUrl: "http://dummyimage.com/207x100.png/5fa2dd/ffffff",
        discountPrice: 26445000,
        type: "Acura",
      },
      {
        id: 14,
        name: "Silverado 3500",
        pictureUrl: "http://dummyimage.com/225x100.png/ff4444/ffffff",
        discountPrice: 5559000,
        type: "Chevrolet",
      },
      {
        id: 15,
        name: "Century",
        pictureUrl: "http://dummyimage.com/165x100.png/5fa2dd/ffffff",
        discountPrice: 13853000,
        type: "Buick",
      },
      {
        id: 16,
        name: "Town & Country",
        pictureUrl: "http://dummyimage.com/129x100.png/5fa2dd/ffffff",
        discountPrice: 54962000,
        type: "Chrysler",
      },
      {
        id: 17,
        name: "Silverado 1500",
        pictureUrl: "http://dummyimage.com/151x100.png/ff4444/ffffff",
        discountPrice: 24400000,
        type: "Chevrolet",
      },
      {
        id: 18,
        name: "Passat",
        pictureUrl: "http://dummyimage.com/121x100.png/5fa2dd/ffffff",
        discountPrice: 58508000,
        type: "Volkswagen",
      },
      {
        id: 19,
        name: "Tracer",
        pictureUrl: "http://dummyimage.com/227x100.png/cc0000/ffffff",
        discountPrice: 46739000,
        type: "Mercury",
      },
      {
        id: 20,
        name: "Town & Country",
        pictureUrl: "http://dummyimage.com/195x100.png/ff4444/ffffff",
        discountPrice: 27531000,
        type: "Chrysler",
      },
      {
        id: 21,
        name: "Dakota",
        pictureUrl: "http://dummyimage.com/112x100.png/5fa2dd/ffffff",
        discountPrice: 97440000,
        type: "Dodge",
      },
      {
        id: 22,
        name: "XJ Series",
        pictureUrl: "http://dummyimage.com/236x100.png/5fa2dd/ffffff",
        discountPrice: 30828000,
        type: "Jaguar",
      },
      {
        id: 23,
        name: "R-Class",
        pictureUrl: "http://dummyimage.com/205x100.png/5fa2dd/ffffff",
        discountPrice: 30505000,
        type: "Mercedes-Benz",
      },
      {
        id: 24,
        name: "Range Rover",
        pictureUrl: "http://dummyimage.com/245x100.png/ff4444/ffffff",
        discountPrice: 50817000,
        type: "Land Rover",
      },
      {
        id: 25,
        name: "Range Rover",
        pictureUrl: "http://dummyimage.com/219x100.png/cc0000/ffffff",
        discountPrice: 3275000,
        type: "Land Rover",
      },
      {
        id: 26,
        name: "Caprice Classic",
        pictureUrl: "http://dummyimage.com/198x100.png/ff4444/ffffff",
        discountPrice: 91674000,
        type: "Chevrolet",
      },
      {
        id: 27,
        name: "4Runner",
        pictureUrl: "http://dummyimage.com/224x100.png/5fa2dd/ffffff",
        discountPrice: 80168000,
        type: "Toyota",
      },
      {
        id: 28,
        name: "TSX",
        pictureUrl: "http://dummyimage.com/162x100.png/ff4444/ffffff",
        discountPrice: 95029000,
        type: "Acura",
      },
      {
        id: 29,
        name: "911",
        pictureUrl: "http://dummyimage.com/125x100.png/cc0000/ffffff",
        discountPrice: 26325000,
        type: "Porsche",
      },
      {
        id: 30,
        name: "Q",
        pictureUrl: "http://dummyimage.com/123x100.png/cc0000/ffffff",
        discountPrice: 81476000,
        type: "Infiniti",
      },
      {
        id: 31,
        name: "Sierra 1500",
        pictureUrl: "http://dummyimage.com/195x100.png/ff4444/ffffff",
        discountPrice: 71893000,
        type: "GMC",
      },
      {
        id: 32,
        name: "Loyale",
        pictureUrl: "http://dummyimage.com/247x100.png/ff4444/ffffff",
        discountPrice: 32273000,
        type: "Subaru",
      },
      {
        id: 33,
        name: "Tacoma",
        pictureUrl: "http://dummyimage.com/162x100.png/cc0000/ffffff",
        discountPrice: 46342000,
        type: "Toyota",
      },
      {
        id: 34,
        name: "Impala",
        pictureUrl: "http://dummyimage.com/163x100.png/ff4444/ffffff",
        discountPrice: 72053000,
        type: "Chevrolet",
      },
      {
        id: 35,
        name: "Vandura G1500",
        pictureUrl: "http://dummyimage.com/245x100.png/ff4444/ffffff",
        discountPrice: 86027000,
        type: "GMC",
      },
      {
        id: 36,
        name: "Sable",
        pictureUrl: "http://dummyimage.com/221x100.png/5fa2dd/ffffff",
        discountPrice: 68437000,
        type: "Mercury",
      },
    ],
  },
  {
    itemsPerPage: DEFAULT_ITEM_PER_PAGE,
    total: 1000,
    hasMore: true,
    productList: [
      {
        id: 37,
        name: "Firebird",
        pictureUrl: "http://dummyimage.com/123x100.png/dddddd/000000",
        discountPrice: 81129000,
        type: "Pontiac",
      },
      {
        id: 38,
        name: "Xterra",
        pictureUrl: "http://dummyimage.com/149x100.png/ff4444/ffffff",
        discountPrice: 8303000,
        type: "Nissan",
      },
      {
        id: 39,
        name: "Tracer",
        pictureUrl: "http://dummyimage.com/179x100.png/ff4444/ffffff",
        discountPrice: 82059000,
        type: "Mercury",
      },
      {
        id: 40,
        name: "A4",
        pictureUrl: "http://dummyimage.com/237x100.png/5fa2dd/ffffff",
        discountPrice: 59793000,
        type: "Audi",
      },
      {
        id: 41,
        name: "MDX",
        pictureUrl: "http://dummyimage.com/163x100.png/5fa2dd/ffffff",
        discountPrice: 50663000,
        type: "Acura",
      },
      {
        id: 42,
        name: "CX-7",
        pictureUrl: "http://dummyimage.com/212x100.png/ff4444/ffffff",
        discountPrice: 266000,
        type: "Mazda",
      },
      {
        id: 43,
        name: "Prius",
        pictureUrl: "http://dummyimage.com/106x100.png/5fa2dd/ffffff",
        discountPrice: 1088000,
        type: "Toyota",
      },
      {
        id: 44,
        name: "Optima",
        pictureUrl: "http://dummyimage.com/121x100.png/ff4444/ffffff",
        discountPrice: 57243000,
        type: "Kia",
      },
      {
        id: 45,
        name: "Scirocco",
        pictureUrl: "http://dummyimage.com/148x100.png/ff4444/ffffff",
        discountPrice: 60188000,
        type: "Volkswagen",
      },
      {
        id: 46,
        name: "Tracer",
        pictureUrl: "http://dummyimage.com/225x100.png/dddddd/000000",
        discountPrice: 36473000,
        type: "Mercury",
      },
      {
        id: 47,
        name: "Ascender",
        pictureUrl: "http://dummyimage.com/141x100.png/5fa2dd/ffffff",
        discountPrice: 26715000,
        type: "Isuzu",
      },
      {
        id: 48,
        name: "Elise",
        pictureUrl: "http://dummyimage.com/238x100.png/5fa2dd/ffffff",
        discountPrice: 22991000,
        type: "Lotus",
      },
      {
        id: 49,
        name: "4Runner",
        pictureUrl: "http://dummyimage.com/138x100.png/5fa2dd/ffffff",
        discountPrice: 70935000,
        type: "Toyota",
      },
      {
        id: 50,
        name: "900",
        pictureUrl: "http://dummyimage.com/147x100.png/dddddd/000000",
        discountPrice: 56426000,
        type: "Saab",
      },
      {
        id: 51,
        name: "Tundra",
        pictureUrl: "http://dummyimage.com/246x100.png/dddddd/000000",
        discountPrice: 33343000,
        type: "Toyota",
      },
      {
        id: 52,
        name: "300",
        pictureUrl: "http://dummyimage.com/137x100.png/ff4444/ffffff",
        discountPrice: 43009000,
        type: "Chrysler",
      },
      {
        id: 53,
        name: "SLK55 AMG",
        pictureUrl: "http://dummyimage.com/101x100.png/ff4444/ffffff",
        discountPrice: 42289000,
        type: "Mercedes-Benz",
      },
      {
        id: 54,
        name: "Accent",
        pictureUrl: "http://dummyimage.com/137x100.png/dddddd/000000",
        discountPrice: 3653000,
        type: "Hyundai",
      },
      {
        id: 55,
        name: "Silverado 2500",
        pictureUrl: "http://dummyimage.com/134x100.png/ff4444/ffffff",
        discountPrice: 75346000,
        type: "Chevrolet",
      },
      {
        id: 56,
        name: "Intrepid",
        pictureUrl: "http://dummyimage.com/218x100.png/ff4444/ffffff",
        discountPrice: 64610000,
        type: "Dodge",
      },
      {
        id: 57,
        name: "Sierra 1500",
        pictureUrl: "http://dummyimage.com/188x100.png/5fa2dd/ffffff",
        discountPrice: 11358000,
        type: "GMC",
      },
      {
        id: 58,
        name: "S5",
        pictureUrl: "http://dummyimage.com/212x100.png/dddddd/000000",
        discountPrice: 11327000,
        type: "Audi",
      },
      {
        id: 59,
        name: "G55 AMG",
        pictureUrl: "http://dummyimage.com/185x100.png/cc0000/ffffff",
        discountPrice: 55949000,
        type: "Mercedes-Benz",
      },
      {
        id: 60,
        name: "Electra",
        pictureUrl: "http://dummyimage.com/180x100.png/ff4444/ffffff",
        discountPrice: 17375000,
        type: "Buick",
      },
      {
        id: 61,
        name: "GTI",
        pictureUrl: "http://dummyimage.com/120x100.png/dddddd/000000",
        discountPrice: 82101000,
        type: "Volkswagen",
      },
      {
        id: 62,
        name: "Eurovan",
        pictureUrl: "http://dummyimage.com/164x100.png/5fa2dd/ffffff",
        discountPrice: 82063000,
        type: "Volkswagen",
      },
      {
        id: 63,
        name: "Ram 3500",
        pictureUrl: "http://dummyimage.com/115x100.png/dddddd/000000",
        discountPrice: 48767000,
        type: "Dodge",
      },
      {
        id: 64,
        name: "Skylark",
        pictureUrl: "http://dummyimage.com/249x100.png/cc0000/ffffff",
        discountPrice: 54973000,
        type: "Buick",
      },
      {
        id: 65,
        name: "Alcyone SVX",
        pictureUrl: "http://dummyimage.com/213x100.png/cc0000/ffffff",
        discountPrice: 69863000,
        type: "Subaru",
      },
      {
        id: 66,
        name: "Santa Fe",
        pictureUrl: "http://dummyimage.com/228x100.png/ff4444/ffffff",
        discountPrice: 29326000,
        type: "Hyundai",
      },
      {
        id: 67,
        name: "LR2",
        pictureUrl: "http://dummyimage.com/204x100.png/ff4444/ffffff",
        discountPrice: 83721000,
        type: "Land Rover",
      },
      {
        id: 68,
        name: "Corvette",
        pictureUrl: "http://dummyimage.com/248x100.png/dddddd/000000",
        discountPrice: 64306000,
        type: "Chevrolet",
      },
      {
        id: 69,
        name: "E-Class",
        pictureUrl: "http://dummyimage.com/138x100.png/ff4444/ffffff",
        discountPrice: 75404000,
        type: "Mercedes-Benz",
      },
      {
        id: 70,
        name: "Q5",
        pictureUrl: "http://dummyimage.com/249x100.png/cc0000/ffffff",
        discountPrice: 50218000,
        type: "Audi",
      },
      {
        id: 71,
        name: "Savana 2500",
        pictureUrl: "http://dummyimage.com/198x100.png/5fa2dd/ffffff",
        discountPrice: 81350000,
        type: "GMC",
      },
      {
        id: 72,
        name: "Safari",
        pictureUrl: "http://dummyimage.com/245x100.png/ff4444/ffffff",
        discountPrice: 94702000,
        type: "GMC",
      },
    ],
  },
]

export const category = [
  { id: 1, type: "Kia" },
  { id: 2, type: "Nissan" },
  { id: 3, type: "Ford" },
  { id: 4, type: "Toyota" },
  { id: 5, type: "Pontiac" },
  { id: 6, type: "GMC" },
  { id: 7, type: "Chrysler" },
  { id: 8, type: "Lincoln" },
  { id: 9, type: "Volkswagen" },
  { id: 10, type: "Hyundai" },
  { id: 11, type: "Land Rover" },
  { id: 12, type: "Chevrolet" },
  { id: 13, type: "Buick" },
  { id: 14, type: "Mazda" },
  { id: 15, type: "Dodge" },
  { id: 16, type: "Subaru" },
  { id: 17, type: "Mercury" },
  { id: 18, type: "Jaguar" },
  { id: 19, type: "Porsche" },
  { id: 20, type: "BMW" },
  { id: 21, type: "Audi" },
  { id: 22, type: "Mercedes-Benz" },
  { id: 23, type: "Acura" },
  { id: 24, type: "Isuzu" },
]

export const productDetail = [
  {
    id: 9,
    name: "Ergonomic Concrete Computer",
    pictureUrl: "https://cf.shopee.vn/file/af7d81b099603a2f8cadaee6e955f28d",
    detailPicsUrl: [
      "https://cf.shopee.vn/file/d8f16516b0aa61ecb03673da477ea26e",
      "https://cf.shopee.vn/file/a02429f6f46de0b5af8d4f5f71ea8199",
    ],
    price: "29.36",
    discountPrice: "66.50",
    rating: 3.2,
    review: 24,
    sold: 774,
    detail: {
      trademark: "McMurdo Station",
      warrantyPeriod: 59,
      warrantyType: "",
      laptopType: "other",
      status: "new",
      quantity: 397,
      sendFrom: "Al Ḩadd",
    },
    description:
      "ex adipisicing consectetur sit veniam veniam cupidatat labore sint ad sint minim laborum qui ut nulla aute exercitation in excepteur qui sunt pariatur dolor dolore laboris ipsum est proident laboris anim proident proident ex aliqua pariatur nulla proident cillum fugiat ad anim minim magna ad laboris sit officia aliquip Lorem laboris magna sit ea officia qui irure enim tempor dolor deserunt ipsum et laborum tempor do nisi ea commodo nulla et non tempor magna occaecat consectetur minim Lorem anim dolor culpa exercitation fugiat nisi cupidatat nulla ea deserunt veniam reprehenderit ad tempor nisi ullamco labore id officia incididunt aliqua amet nisi id nostrud voluptate adipisicing proident enim quis ullamco commodo fugiat est aliquip occaecat minim voluptate dolor excepteur aliquip voluptate eu quis et culpa magna irure veniam deserunt est anim ipsum nostrud consectetur cillum elit nostrud id adipisicing Lorem est cillum ullamco cillum in Lorem anim qui aliqua consectetur excepteur ad culpa reprehenderit nulla tempor consequat veniam id dolor veniam anim ea exercitation non commodo laboris est non cillum et consectetur adipisicing commodo ex reprehenderit cillum consectetur eiusmod ipsum in est ipsum Lorem nostrud in excepteur sunt in exercitation duis exercitation dolor non aliqua laboris in magna nisi in fugiat incididunt sunt pariatur consequat fugiat amet esse reprehenderit culpa sunt magna commodo ex eu eiusmod esse sunt eiusmod aute consequat mollit enim laboris et velit mollit sunt consequat",
    type: "LeBaron",
  },
  {
    id: 1,
    name: "Ergonomic Plastic Table",
    pictureUrl: "https://cf.shopee.vn/file/a02429f6f46de0b5af8d4f5f71ea8199",
    detailPicsUrl: [
      "https://cf.shopee.vn/file/bcab2156afe7704bdf5a01577b2c8422",
      "https://cf.shopee.vn/file/bcab2156afe7704bdf5a01577b2c8422",
      "https://cf.shopee.vn/file/d1fae5bae7153be96056fa2b7e59d650",
      "https://cf.shopee.vn/file/a02429f6f46de0b5af8d4f5f71ea8199",
      "https://cf.shopee.vn/file/d8f16516b0aa61ecb03673da477ea26e",
    ],
    price: "19.89",
    discountPrice: "73.85",
    rating: 2.9,
    review: 866,
    sold: 475,
    detail: {
      trademark: "Ísafjörður",
      warrantyPeriod: 67,
      warrantyType: "amet",
      laptopType: "other",
      status: "new",
      quantity: 82,
      sendFrom: "Greymouth",
    },
    description:
      "irure aute pariatur qui amet voluptate excepteur excepteur eiusmod id nulla velit quis laborum ullamco proident aute pariatur ea ipsum reprehenderit non ex adipisicing mollit incididunt id in proident nisi adipisicing deserunt quis consectetur mollit do dolor anim fugiat pariatur laborum qui id minim laboris cupidatat sunt aliqua quis do amet ipsum incididunt ullamco fugiat ipsum sint deserunt et esse nulla quis esse sunt ea sunt reprehenderit tempor id elit ipsum in nostrud dolore pariatur occaecat nisi excepteur ut anim consequat anim do ullamco dolore enim velit irure cillum exercitation qui amet veniam aute veniam reprehenderit minim Lorem laboris exercitation duis dolore ipsum elit fugiat deserunt in irure irure eiusmod Lorem adipisicing sunt et aute nostrud excepteur tempor elit mollit mollit dolor aliquip cupidatat incididunt occaecat amet minim eiusmod ad esse et nisi velit mollit dolore qui incididunt ad sit anim consequat minim ea consectetur id proident cillum excepteur sit veniam eu proident eu veniam culpa aute nulla non qui sit Lorem consequat magna nulla in eiusmod duis velit irure culpa nulla aliquip est",
    type: "A8",
  },
  {
    id: 2,
    name: "Tasty Granite Towels",
    pictureUrl: "https://cf.shopee.vn/file/bcab2156afe7704bdf5a01577b2c8422",
    detailPicsUrl: [
      "https://cf.shopee.vn/file/af7d81b099603a2f8cadaee6e955f28d",
      "https://cf.shopee.vn/file/a02429f6f46de0b5af8d4f5f71ea8199",
      "https://cf.shopee.vn/file/af7d81b099603a2f8cadaee6e955f28d",
      "https://cf.shopee.vn/file/d1fae5bae7153be96056fa2b7e59d650",
    ],
    price: "81.33",
    discountPrice: "95.60",
    rating: 4.2,
    review: 692,
    sold: 760,
    detail: {
      trademark: "Sylivainiótika",
      warrantyPeriod: 77,
      warrantyType: "duis adipisicing",
      laptopType: "other",
      status: "secondHand",
      quantity: 232,
      sendFrom: "Nikšić",
    },
    description:
      "pariatur eu enim minim et irure ea excepteur voluptate mollit et laborum minim irure in commodo excepteur incididunt ad laboris non cillum ea consectetur consectetur sunt officia minim aute culpa dolor pariatur sint enim officia sit eiusmod labore ut adipisicing do ea amet occaecat non et eiusmod dolor reprehenderit nostrud labore velit occaecat fugiat elit aute adipisicing do magna tempor ut laboris amet sit mollit commodo ad ad pariatur elit id sunt nulla sint aute laboris eu reprehenderit voluptate cillum amet sunt adipisicing quis ex dolore eiusmod Lorem proident anim do id sint anim occaecat anim officia nisi tempor adipisicing non consequat proident eu commodo ut pariatur minim consequat anim non consectetur commodo magna magna anim excepteur ea enim sint deserunt excepteur labore anim eu dolore ea enim dolor consequat aute fugiat minim pariatur esse laborum anim qui aliquip laboris ad et pariatur ipsum cillum id incididunt deserunt adipisicing occaecat dolore consequat minim enim sint officia proident amet labore laborum dolor deserunt elit culpa enim deserunt ex aliqua",
    type: "Aventador",
  },
  {
    id: 3,
    name: "Gorgeous Wooden Pants",
    pictureUrl: "https://cf.shopee.vn/file/d1fae5bae7153be96056fa2b7e59d650",
    detailPicsUrl: [
      "https://cf.shopee.vn/file/d8f16516b0aa61ecb03673da477ea26e",
      "https://cf.shopee.vn/file/a02429f6f46de0b5af8d4f5f71ea8199",
      "https://cf.shopee.vn/file/af7d81b099603a2f8cadaee6e955f28d",
      "https://cf.shopee.vn/file/d1fae5bae7153be96056fa2b7e59d650",
      "https://cf.shopee.vn/file/d1fae5bae7153be96056fa2b7e59d650",
      "https://cf.shopee.vn/file/a02429f6f46de0b5af8d4f5f71ea8199",
      "https://cf.shopee.vn/file/af7d81b099603a2f8cadaee6e955f28d",
    ],
    price: "76.56",
    discountPrice: "33.72",
    rating: 3.6,
    review: 633,
    sold: 467,
    detail: {
      trademark: "Deh Khwāhān",
      warrantyPeriod: 58,
      warrantyType: "",
      laptopType: "other",
      status: "new",
      quantity: 47,
      sendFrom: "Tubmanburg",
    },
    description:
      "minim voluptate proident ipsum cupidatat et sint minim minim dolore incididunt exercitation amet laboris pariatur dolor ex est adipisicing cillum nulla ex fugiat minim cupidatat proident ipsum sit sunt eiusmod nostrud in excepteur proident irure adipisicing quis deserunt consequat do cillum occaecat occaecat esse pariatur veniam laborum pariatur dolor velit amet nisi elit cillum et duis est adipisicing qui est cillum labore fugiat ut ea ea esse pariatur aliquip ea deserunt culpa aliqua mollit Lorem irure in incididunt veniam est laboris enim tempor voluptate ad ex cupidatat qui consectetur excepteur excepteur reprehenderit ipsum in officia Lorem officia in incididunt fugiat non qui ullamco et nisi amet eu esse cillum velit exercitation laboris consequat id sit Lorem mollit veniam tempor nostrud ea eiusmod proident enim aute ut culpa irure voluptate pariatur est elit ipsum qui cupidatat reprehenderit Lorem nulla occaecat sint irure Lorem magna anim anim ullamco ad excepteur Lorem excepteur aliqua fugiat id sit sint mollit reprehenderit culpa non est pariatur sint tempor minim non elit consectetur Lorem do veniam do ea laboris cillum eiusmod eiusmod aliqua commodo elit velit dolore ea laboris nostrud dolore id consequat deserunt mollit ullamco officia dolore veniam nulla deserunt non dolore sit elit consequat exercitation enim velit fugiat ea ut incididunt consequat cupidatat proident est voluptate eu ut quis nostrud consectetur reprehenderit do nostrud ad ea reprehenderit labore velit duis proident sunt veniam id veniam est duis sit incididunt consequat id deserunt aliqua dolore aliquip culpa ad elit qui dolor deserunt et officia id pariatur non excepteur cupidatat commodo amet non",
    type: "LeBaron",
  },
  {
    id: 4,
    name: "Gorgeous Concrete Car",
    pictureUrl: "https://cf.shopee.vn/file/bcab2156afe7704bdf5a01577b2c8422",
    detailPicsUrl: [
      "https://cf.shopee.vn/file/af7d81b099603a2f8cadaee6e955f28d",
    ],
    price: "53.56",
    discountPrice: "55.95",
    rating: 4.6,
    review: 534,
    sold: 963,
    detail: {
      trademark: "Na Kluea",
      warrantyPeriod: 30,
      warrantyType: "ad elit",
      laptopType: "other",
      status: "secondHand",
      quantity: 73,
      sendFrom: "Bayanhongor",
    },
    description:
      "qui qui irure culpa incididunt nostrud tempor aliquip nulla officia nulla laborum Lorem deserunt eiusmod aute aute aliquip qui enim deserunt dolore elit proident et irure esse laborum nostrud aliquip quis voluptate quis deserunt et officia velit nulla eu quis nulla minim occaecat aliqua cupidatat non eu ad excepteur nisi adipisicing dolore quis nulla fugiat reprehenderit excepteur culpa dolor ex aute ipsum aute anim elit id mollit non incididunt Lorem fugiat enim irure aliqua quis ea nulla nulla nostrud enim tempor ullamco sit adipisicing ut aliquip dolore do officia sint eu id magna commodo proident adipisicing velit labore do amet mollit mollit voluptate reprehenderit ipsum eu nulla sint officia consectetur enim occaecat nulla sit pariatur cupidatat sit et velit id est eiusmod ad nulla elit eiusmod voluptate voluptate nisi mollit dolore ullamco esse laborum consectetur nostrud ad deserunt ad deserunt est cillum do nostrud ad ad minim magna nulla consequat excepteur non amet dolore eu laborum magna aliquip labore ullamco aliquip dolor velit magna laboris elit Lorem quis tempor nulla est qui commodo tempor incididunt minim elit nostrud proident nisi ad sunt pariatur duis ex cupidatat laborum ea esse aute Lorem ut aute elit adipisicing anim eiusmod esse incididunt laboris pariatur proident adipisicing exercitation aliquip occaecat est ut ut veniam in eiusmod laboris elit excepteur consequat nostrud labore irure anim consequat id magna eiusmod amet ullamco mollit ea aliqua cillum culpa Lorem quis et ullamco do et exercitation ipsum proident velit ad quis aliquip eiusmod tempor irure laboris in id id culpa fugiat deserunt aliquip laborum proident nostrud consectetur veniam aliqua duis in adipisicing id et in velit ullamco exercitation aliquip consequat in pariatur commodo culpa Lorem anim enim nisi elit minim laborum culpa occaecat exercitation cupidatat deserunt esse esse",
    type: "Silverado",
  },
  {
    id: 5,
    name: "Ergonomic Metal Fish",
    pictureUrl: "https://cf.shopee.vn/file/bcab2156afe7704bdf5a01577b2c8422",
    detailPicsUrl: [
      "https://cf.shopee.vn/file/a02429f6f46de0b5af8d4f5f71ea8199",
    ],
    price: "53.79",
    discountPrice: "93.65",
    rating: 2.4,
    review: 109,
    sold: 734,
    detail: {
      trademark: "Kingston",
      warrantyPeriod: 37,
      warrantyType: "nisi",
      laptopType: "other",
      status: "secondHand",
      quantity: 89,
      sendFrom: "Ambodifotatra",
    },
    description:
      "deserunt aute veniam incididunt ea fugiat cupidatat pariatur consectetur enim do ipsum pariatur labore veniam fugiat ipsum elit do ea laboris mollit anim ad ex elit consectetur cillum incididunt Lorem pariatur cillum nisi amet nostrud dolor excepteur anim nostrud veniam et qui proident laborum elit laboris fugiat aute elit aliqua eu veniam magna laboris reprehenderit consequat commodo eu aliquip velit adipisicing quis nisi officia excepteur laboris ad mollit duis commodo ipsum reprehenderit laboris in ipsum cillum dolore aliquip ea minim velit reprehenderit dolor adipisicing et culpa est occaecat nulla velit aliqua reprehenderit labore velit quis qui consectetur commodo ut magna consectetur est cillum amet Lorem incididunt excepteur ullamco sunt voluptate pariatur est elit consequat officia minim sunt nisi adipisicing enim irure sunt eu excepteur ex dolore eu dolore officia sint eu ut culpa nostrud eu incididunt cillum et magna sit adipisicing amet laboris aliqua voluptate ad exercitation amet eiusmod incididunt anim velit eu esse in qui anim reprehenderit fugiat reprehenderit reprehenderit anim et nisi excepteur aute cillum mollit sit elit eu eu dolore magna dolor ipsum sint labore exercitation irure dolore laboris reprehenderit id nulla nulla non velit velit ut ea tempor est Lorem cillum aliqua non Lorem ea tempor magna sit et mollit proident elit culpa sint qui eiusmod in et sit consequat commodo ullamco quis cillum proident incididunt incididunt exercitation velit excepteur in exercitation veniam nostrud in labore sint incididunt officia officia qui anim in officia velit quis veniam nostrud culpa esse irure adipisicing occaecat est aliqua quis qui exercitation mollit occaecat magna ad sint esse in",
    type: "Charger",
  },
  {
    id: 6,
    name: "Awesome Rubber Table",
    pictureUrl: "https://cf.shopee.vn/file/a02429f6f46de0b5af8d4f5f71ea8199",
    detailPicsUrl: [
      "https://cf.shopee.vn/file/af7d81b099603a2f8cadaee6e955f28d",
      "https://cf.shopee.vn/file/a02429f6f46de0b5af8d4f5f71ea8199",
      "https://cf.shopee.vn/file/a02429f6f46de0b5af8d4f5f71ea8199",
    ],
    price: "19.27",
    discountPrice: "35.38",
    rating: 2.2,
    review: 404,
    sold: 939,
    detail: {
      trademark: "Ciudad del Este",
      warrantyPeriod: 11,
      warrantyType: "dolore duis qui",
      laptopType: "other",
      status: "secondHand",
      quantity: 125,
      sendFrom: "Sami",
    },
    description:
      "commodo laboris reprehenderit non esse dolor tempor labore amet incididunt enim esse duis dolor incididunt ipsum eu et qui consectetur qui nostrud labore esse minim do elit velit cupidatat adipisicing amet sunt proident proident exercitation in qui adipisicing commodo cillum sint laboris dolor labore voluptate velit est do Lorem occaecat nisi id ea cillum excepteur nostrud cillum et ea proident aute aute laboris cillum consectetur sint dolore voluptate aliqua laborum et exercitation irure culpa officia est veniam laboris magna dolore culpa enim reprehenderit est commodo nulla amet deserunt do id pariatur nisi adipisicing eiusmod ad adipisicing culpa deserunt duis dolore excepteur non labore proident consequat irure ut adipisicing commodo irure eu fugiat minim est amet tempor cillum ex in nulla sit ad reprehenderit incididunt est nisi et incididunt dolor occaecat amet elit esse nostrud esse aute aliquip irure aliquip veniam id sit adipisicing",
    type: "Civic",
  },
  {
    id: 7,
    name: "Unbranded Granite Pants",
    pictureUrl: "https://cf.shopee.vn/file/d1fae5bae7153be96056fa2b7e59d650",
    detailPicsUrl: [
      "https://cf.shopee.vn/file/af7d81b099603a2f8cadaee6e955f28d",
      "https://cf.shopee.vn/file/d1fae5bae7153be96056fa2b7e59d650",
      "https://cf.shopee.vn/file/d1fae5bae7153be96056fa2b7e59d650",
      "https://cf.shopee.vn/file/d1fae5bae7153be96056fa2b7e59d650",
      "https://cf.shopee.vn/file/a02429f6f46de0b5af8d4f5f71ea8199",
    ],
    price: "40.62",
    discountPrice: "79.50",
    rating: 2.5,
    review: 683,
    sold: 32,
    detail: {
      trademark: "Dorp Tera Kora",
      warrantyPeriod: 43,
      warrantyType: "",
      laptopType: "other",
      status: "secondHand",
      quantity: 341,
      sendFrom: "Escuintla",
    },
    description:
      "anim irure Lorem in proident in consequat reprehenderit et consectetur pariatur culpa cillum non dolore incididunt consectetur do veniam laboris cupidatat ullamco aliqua anim ex cillum incididunt duis deserunt anim labore consectetur ipsum laborum ullamco duis laboris magna veniam ipsum adipisicing ex adipisicing reprehenderit et ut in cupidatat occaecat pariatur cillum Lorem qui enim nostrud enim amet consequat aliquip amet cillum enim anim esse voluptate et excepteur sint elit dolore nulla pariatur aliqua elit sint ea in consequat cupidatat ullamco ad nostrud mollit qui voluptate irure adipisicing sint nisi esse aute nulla fugiat voluptate amet minim dolor mollit ut anim in sit et aliqua laborum non tempor magna anim sint occaecat ipsum do occaecat in do mollit ad dolor magna dolor dolor laboris pariatur voluptate pariatur occaecat Lorem duis nulla minim labore esse id non sint adipisicing sit pariatur ad anim est eu enim irure est exercitation ad deserunt mollit elit nostrud in duis dolore deserunt nostrud dolore tempor tempor quis nisi nostrud do est cupidatat duis reprehenderit cupidatat proident velit in irure ipsum exercitation",
    type: "Charger",
  },
  {
    id: 8,
    name: "Licensed Plastic Fish",
    pictureUrl: "https://cf.shopee.vn/file/bcab2156afe7704bdf5a01577b2c8422",
    detailPicsUrl: [
      "https://cf.shopee.vn/file/a02429f6f46de0b5af8d4f5f71ea8199",
      "https://cf.shopee.vn/file/a02429f6f46de0b5af8d4f5f71ea8199",
      "https://cf.shopee.vn/file/d8f16516b0aa61ecb03673da477ea26e",
    ],
    price: "10.38",
    discountPrice: "6.03",
    rating: 0.1,
    review: 695,
    sold: 844,
    detail: {
      trademark: "Oranjestad",
      warrantyPeriod: 64,
      warrantyType: "ad laborum",
      laptopType: "other",
      status: "secondHand",
      quantity: 436,
      sendFrom: "Espargos",
    },
    description:
      "qui magna et exercitation incididunt sint excepteur laboris incididunt laboris pariatur non elit irure nulla est sunt ad incididunt et qui occaecat nostrud duis proident duis deserunt labore ipsum esse quis sint eiusmod occaecat minim labore labore adipisicing amet laboris sunt irure labore commodo adipisicing ullamco et esse excepteur tempor quis aute velit id non fugiat dolore et laborum ea Lorem ullamco dolor adipisicing reprehenderit laboris duis nisi nisi id magna reprehenderit incididunt aliqua et fugiat proident duis dolor enim exercitation sunt labore proident magna elit est enim amet eiusmod qui amet excepteur reprehenderit fugiat minim do dolore tempor ut fugiat amet ipsum dolore ex cupidatat reprehenderit pariatur irure ex fugiat cillum proident in dolor fugiat enim deserunt dolor eu amet amet laboris fugiat consequat consequat mollit aliqua consequat Lorem id eiusmod aute occaecat laboris deserunt ea adipisicing reprehenderit ex nisi do laboris cupidatat sunt ullamco labore aute enim occaecat anim non mollit magna fugiat adipisicing elit consequat commodo consequat sit incididunt aliquip eu cillum id sit sit laborum et reprehenderit dolor ea duis officia sit ullamco mollit officia consectetur non id officia et ad mollit exercitation qui ullamco aliquip non commodo proident cupidatat reprehenderit nulla sit occaecat dolor enim pariatur aute commodo id Lorem commodo quis dolor ea cillum minim incididunt tempor cillum qui quis cupidatat veniam occaecat officia excepteur laboris ex ad ea est consectetur dolore esse est aliqua ipsum sint pariatur",
    type: "Alpine",
  },
]

export const checkedProductList = [
  {
    id: 3,
    name: "Gorgeous Wooden Pants",
    pictureUrl: "https://cf.shopee.vn/file/d1fae5bae7153be96056fa2b7e59d650",
    price: "76.56",
    discountPrice: "33.72",
    type: "LeBaron",
    qty: 1,
  },
  {
    id: 4,
    name: "Gorgeous Concrete Car",
    pictureUrl: "https://cf.shopee.vn/file/bcab2156afe7704bdf5a01577b2c8422",
    price: "53.56",
    discountPrice: "55.95",
    type: "Silverado",
    qty: 3,
  },
  {
    id: 5,
    name: "Ergonomic Metal Fish",
    pictureUrl: "https://cf.shopee.vn/file/bcab2156afe7704bdf5a01577b2c8422",
    price: "53.79",
    discountPrice: "93.65",
    type: "Charger",
    qty: 2,
  },
]

export const laptopType = [
  {
    id: 1,
    name: "Gaming",
  },
  {
    id: 2,
    name: "Ultrabook",
  },
]

export const trademarks = [
  {
    id: 1,
    trademarkName: "Apple",
  },
  {
    id: 2,
    trademarkName: "Asus",
  },
  {
    id: 3,
    trademarkName: "Dell",
  },
  {
    id: 4,
    trademarkName: "HP",
  },
  {
    id: 5,
    trademarkName: "Lenovo",
  },
  {
    id: 6,
    trademarkName: "MSI",
  },
]

export const productStatus = [
  { id: 1, status: "newStatus" },
  { id: 2, status: "secondHandStatus" },
]
