export const MAX_LENGTH_PRODUCT_NAME = 120
export const MIN_LENGTH_PRODUCT_NAME = 10
export const MAX_PREPARE_TIME = 15
export const MIN_PREPARE_TIME = 7
export const MAX_LENGTH_PRODUCT_DESCRIPTION = 3000
export const MIN_LENGTH_PRODUCT_DESCRIPTION = 10
